export const RESEARCH_LAB_DEFAULT_PROMPT_CONFIG_ID = "research-lab-prompt-default-v1";
export const RESEARCH_LAB_DEFAULT_EVIDENCE_PROFILE_ID = "research-lab-evidence-default-v1";

export const RESEARCH_LAB_HEARTBEAT_INTERVAL_MS = 10_000;
export const RESEARCH_LAB_HEARTBEAT_STALE_MS = 60_000;
export const RESEARCH_LAB_EXECUTION_STALE_SECONDS = Math.ceil(RESEARCH_LAB_HEARTBEAT_STALE_MS / 1000);
export const RESEARCH_LAB_STREAM_REFRESH_MS = 3_000;

export const RESEARCH_LAB_PERPLEXITY_TIMEOUT_MS = 12_000;
export const RESEARCH_LAB_ANTHROPIC_TIMEOUT_MS = 45_000;
export const RESEARCH_LAB_ANTHROPIC_MAX_ATTEMPTS = 2;
export const RESEARCH_LAB_ANTHROPIC_MAX_TOKENS = 1600;
export const RESEARCH_LAB_SYNTHESIS_MAX_PROMPT_CHARS = 10_000;
export const RESEARCH_LAB_MAX_TICKERS_PER_RUN = 20;
export const RESEARCH_LAB_RESULTS_EVENT_LIMIT = 100;
export const RESEARCH_LAB_DEFAULT_MAX_QUERY_FAMILIES = 4;
export const RESEARCH_LAB_DEFAULT_EVIDENCE_TARGET = 8;
export const RESEARCH_LAB_DEFAULT_FORCE_FRESH_SEARCH = false;
