export type EtfCatalogEntry = {
  ticker: string;
  sector: string;
  industry: string;
  exactUrl: string;
};

export const ETF_CATALOG: EtfCatalogEntry[] = [
  { ticker: "SLX", sector: "Materials", industry: "Steel", exactUrl: "https://www.vaneck.com/us/en/investments/steel-etf-slx/" },
  { ticker: "SMH", sector: "Information Technology", industry: "Semiconductors", exactUrl: "https://www.vaneck.com/us/en/investments/semiconductor-etf-smh/" },
  { ticker: "IYR", sector: "Real Estate", industry: "Real Estate", exactUrl: "https://www.ishares.com/us/products/239520/ishares-us-real-estate-etf" },
  { ticker: "IYE", sector: "Energy", industry: "Integrated Energy", exactUrl: "https://www.ishares.com/us/products/239507/ishares-us-energy-etf" },
  { ticker: "BKX", sector: "Financials", industry: "Banking", exactUrl: "https://indexes.nasdaqomx.com/Index/Weighting/BKX" },
  { ticker: "XOI", sector: "Energy", industry: "Integrated Oil & Gas", exactUrl: "https://finance.yahoo.com/quote/%5EXOI/components/" },
  { ticker: "NWX", sector: "Materials", industry: "Coal", exactUrl: "https://finance.yahoo.com/quote/%5ENWX/components/" },
  { ticker: "XNG", sector: "Energy", industry: "Natural Gas", exactUrl: "https://www.investing.com/indices/arca-natural-gas-components" },
  { ticker: "INSR", sector: "Financials", industry: "Insurance", exactUrl: "https://indexes.nasdaqomx.com/Index/Overview/INSR" },
  { ticker: "OIH", sector: "Energy", industry: "Oil Services", exactUrl: "https://www.vaneck.com/us/en/investments/oil-services-etf-oih/" },
  { ticker: "VNQ", sector: "Real Estate", industry: "Real Estate", exactUrl: "https://investor.vanguard.com/investment-products/etfs/profile/vnq" },
  { ticker: "XAU", sector: "Materials", industry: "Gold & Silver Mining", exactUrl: "https://indexes.nasdaqomx.com/Index/Overview/XAU" },
  { ticker: "SOXX", sector: "Information Technology", industry: "Semiconductors", exactUrl: "https://www.ishares.com/us/products/239705/ishares-phlx-semiconductor-etf" },
  { ticker: "OSX", sector: "Energy", industry: "Oil Services", exactUrl: "https://indexes.nasdaqomx.com/Index/Overview/OSX" },
  { ticker: "UFO", sector: "Industrials", industry: "Space & Satellites", exactUrl: "https://procureetfs.com/ufo/" },
  { ticker: "TAN", sector: "Energy", industry: "Clean Energy", exactUrl: "https://www.invesco.com/us/en/financial-products/etfs/invesco-solar-etf.html" },
  { ticker: "IBUY", sector: "Consumer Discretionary", industry: "Online Retail", exactUrl: "https://amplifyetfs.com/ibuy-holdings/" },
  { ticker: "QQQE", sector: "Multi-Sector", industry: "Nasdaq-100 Equal Weight", exactUrl: "https://www.direxion.com/product/nasdaq-100-equal-weighted-index-etf" },
  { ticker: "JETS", sector: "Industrials", industry: "Airlines", exactUrl: "https://usglobaletfs.com/fund/u-s-global-jets-etf/" },
  { ticker: "IBB", sector: "Health Care", industry: "Biotechnology", exactUrl: "https://www.ishares.com/us/products/239699/ishares-biotechnology-etf" },
  { ticker: "CIBR", sector: "Information Technology", industry: "Cybersecurity", exactUrl: "https://www.ftportfolios.com/Retail/Etf/EtfHoldings.aspx?Ticker=CIBR" },
  { ticker: "UTES", sector: "Utilities", industry: "Utilities", exactUrl: "https://www.virtus.com/our-products/individual-investors/virtus-reaves-utilities-etf" },
  { ticker: "ROBO", sector: "Industrials", industry: "Robotics & Automation", exactUrl: "https://www.roboglobaletfs.com/robo" },
  { ticker: "IGV", sector: "Information Technology", industry: "Software", exactUrl: "https://www.ishares.com/us/products/239750/ishares-expanded-tech-software-sector-etf" },
  { ticker: "WCLD", sector: "Information Technology", industry: "Cloud Computing", exactUrl: "https://www.wisdomtree.com/investments/etfs/equity/wcld" },
  { ticker: "ITA", sector: "Industrials", industry: "Aerospace & Defense", exactUrl: "https://www.ishares.com/us/products/239502/ishares-us-aerospace-defense-etf" },
  { ticker: "PAVE", sector: "Industrials", industry: "Infrastructure Development", exactUrl: "https://www.globalxetfs.com/funds/pave/" },
  { ticker: "BLOK", sector: "Financials", industry: "Blockchain & Digital Assets", exactUrl: "https://amplifyetfs.com/blok-holdings/" },
  { ticker: "AIQ", sector: "Information Technology", industry: "Artificial Intelligence", exactUrl: "https://www.globalxetfs.com/funds/aiq/" },
  { ticker: "IYZ", sector: "Communication Services", industry: "Telecommunications", exactUrl: "https://www.ishares.com/us/products/239523/ishares-us-telecommunications-etf" },
  { ticker: "PEJ", sector: "Consumer Discretionary", industry: "Leisure & Entertainment", exactUrl: "https://www.invesco.com/us/en/financial-products/etfs/invesco-leisure-and-entertainment-etf.html" },
  { ticker: "FDN", sector: "Communication Services", industry: "Internet", exactUrl: "https://www.ftportfolios.com/Retail/Etf/EtfHoldings.aspx?Ticker=FDN" },
  { ticker: "UNG", sector: "Commodities", industry: "Natural Gas", exactUrl: "https://www.uscfinvestments.com/holdings/ung" },
  { ticker: "BOAT", sector: "Industrials", industry: "Shipping", exactUrl: "https://sonicshares.com/boat/" },
  { ticker: "KWEB", sector: "Communication Services", industry: "China Internet", exactUrl: "https://kraneshares.com/etf/kweb/" },
  { ticker: "IBIT", sector: "Cryptocurrency", industry: "Bitcoin", exactUrl: "https://www.ishares.com/us/products/333011/ishares-bitcoin-trust-etf" },
  { ticker: "IHI", sector: "Health Care", industry: "Medical Devices", exactUrl: "https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf" },
  { ticker: "DRIV", sector: "Consumer Discretionary", industry: "Electric Vehicles", exactUrl: "https://www.globalxetfs.com/funds/driv/" },
  { ticker: "MSOS", sector: "Consumer Staples", industry: "Cannabis", exactUrl: "https://advisorshares.com/wp-content/uploads/csv/holdings/AS_Holdings_File.csv" },
  { ticker: "SOCL", sector: "Communication Services", industry: "Social Media", exactUrl: "https://www.globalxetfs.com/funds/socl/" },
  { ticker: "XLU", sector: "Utilities", industry: "Utilities", exactUrl: "https://www.ssga.com/us/en/intermediary/etfs/state-street-utilities-select-sector-spdr-etf-xlu" },
  { ticker: "ARKF", sector: "Financials", industry: "Fintech Innovation", exactUrl: "https://www.ark-funds.com/funds/arkf" },
  { ticker: "ARKK", sector: "Multi-Sector", industry: "Disruptive Innovation", exactUrl: "https://www.ark-funds.com/funds/arkk" },
  { ticker: "GLD", sector: "Commodities", industry: "Gold", exactUrl: "https://www.spdrgoldshares.com/usa/gld/" },
  { ticker: "GXC", sector: "Multi-Sector", industry: "China Large Cap", exactUrl: "https://www.ssga.com/us/en/intermediary/etfs/state-street-spdr-sp-china-etf-gxc" },
  { ticker: "SCHH", sector: "Real Estate", industry: "Real Estate", exactUrl: "https://www.schwabassetmanagement.com/allholdings/SCHH" },
  { ticker: "GDX", sector: "Materials", industry: "Gold Mining", exactUrl: "https://www.vaneck.com/us/en/investments/gold-miners-etf-gdx/" },
  { ticker: "IPAY", sector: "Financials", industry: "Digital Payments", exactUrl: "https://amplifyetfs.com/ipay-holdings/" },
  { ticker: "IWM", sector: "Multi-Sector", industry: "Small Cap Equities", exactUrl: "https://www.ishares.com/us/products/239710/ishares-russell-2000-etf" },
  { ticker: "EATZ", sector: "Consumer Discretionary", industry: "Restaurants & Food Service", exactUrl: "https://advisorshares.com/etfs/eatz/" },
  { ticker: "FXI", sector: "Multi-Sector", industry: "China Large Cap", exactUrl: "https://www.ishares.com/us/products/239536/ishares-china-largecap-etf" },
  { ticker: "DBA", sector: "Commodities", industry: "Agriculture", exactUrl: "https://www.invesco.com/us/en/financial-products/etfs/invesco-db-agriculture-fund.html" },
  { ticker: "ICLN", sector: "Energy", industry: "Clean Energy", exactUrl: "https://www.ishares.com/us/products/239738/ishares-global-clean-energy-etf" },
  { ticker: "SILJ", sector: "Materials", industry: "Silver Mining", exactUrl: "https://amplifyetfs.com/silj-holdings/" },
  { ticker: "REZ", sector: "Real Estate", industry: "Residential REITs", exactUrl: "https://www.ishares.com/us/products/239545/ishares-residential-real-estate-capped-etf" },
  { ticker: "LIT", sector: "Materials", industry: "Lithium & Battery Technology", exactUrl: "https://www.globalxetfs.com/funds/lit/" },
  { ticker: "SLV", sector: "Commodities", industry: "Silver", exactUrl: "https://www.ishares.com/us/products/239855/ishares-silver-trust-fund" },
  { ticker: "PBJ", sector: "Consumer Staples", industry: "Food & Beverage", exactUrl: "https://www.invesco.com/us/en/financial-products/etfs/invesco-food-beverage-etf.html" },
  { ticker: "USO", sector: "Commodities", industry: "Crude Oil", exactUrl: "https://www.uscfinvestments.com/holdings/uso" },
  { ticker: "DBC", sector: "Commodities", industry: "Broad Commodities", exactUrl: "https://www.invesco.com/us/en/financial-products/etfs/invesco-db-commodity-index-tracking-fund.html" },
  { ticker: "FCG", sector: "Energy", industry: "Natural Gas Exploration & Production", exactUrl: "https://www.ftportfolios.com/Retail/Etf/EtfHoldings.aspx?Ticker=FCG" },
  { ticker: "ARKG", sector: "Health Care", industry: "Genomics", exactUrl: "https://www.ark-funds.com/funds/arkg" },
  { ticker: "CPER", sector: "Commodities", industry: "Copper", exactUrl: "https://www.uscfinvestments.com/holdings/cper" },
  { ticker: "PPH", sector: "Health Care", industry: "Pharmaceuticals", exactUrl: "https://www.invesco.com/us/en/financial-products/etfs/invesco-pharmaceuticals-etf.html" },
  { ticker: "FNGS", sector: "Multi-Sector", industry: "FANG+ Mega Cap Growth", exactUrl: "https://microsectors.com/fang/" },
  { ticker: "URA", sector: "Energy", industry: "Uranium & Nuclear Energy", exactUrl: "https://www.globalxetfs.com/funds/ura/" },
  { ticker: "WGMI", sector: "Information Technology", industry: "Bitcoin Miners", exactUrl: "https://valkyrieinvest.com/etfs/" },
  { ticker: "REMX", sector: "Materials", industry: "Rare Earth & Strategic Metals", exactUrl: "https://www.vaneck.com/us/en/investments/rare-earth-strategic-metals-etf-remx/" },
];

export const ETF_CATALOG_BY_TICKER: Record<string, EtfCatalogEntry> = Object.fromEntries(
  ETF_CATALOG.map((row) => [row.ticker.toUpperCase(), row]),
) as Record<string, EtfCatalogEntry>;

export const EQUAL_WEIGHT_SECTOR_ETFS: Array<{ ticker: string; benchmarkTicker: string }> = [
  { ticker: "RSPC", benchmarkTicker: "XLK" },
  { ticker: "RSPD", benchmarkTicker: "XLV" },
  { ticker: "RSPS", benchmarkTicker: "XLF" },
  { ticker: "RSPG", benchmarkTicker: "XLY" },
  { ticker: "RSPF", benchmarkTicker: "XLP" },
  { ticker: "RSPH", benchmarkTicker: "XLE" },
  { ticker: "RSPN", benchmarkTicker: "XLI" },
  { ticker: "RSPM", benchmarkTicker: "XLB" },
  { ticker: "RSPR", benchmarkTicker: "XLRE" },
  { ticker: "RSPT", benchmarkTicker: "XLU" },
  { ticker: "RSPU", benchmarkTicker: "XLC" },
];

export const ETF_CATALOG_TICKERS = ETF_CATALOG.map((row) => row.ticker);
