CREATE TABLE IF NOT EXISTS etf_watchlists (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  list_type TEXT NOT NULL CHECK (list_type IN ('sector', 'industry')),
  parent_sector TEXT,
  industry TEXT,
  ticker TEXT NOT NULL,
  fund_name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(list_type, ticker)
);

CREATE TABLE IF NOT EXISTS etf_constituents (
  id TEXT PRIMARY KEY,
  etf_ticker TEXT NOT NULL,
  constituent_ticker TEXT NOT NULL,
  constituent_name TEXT,
  weight REAL,
  as_of_date TEXT,
  source TEXT NOT NULL,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(etf_ticker, constituent_ticker)
);

CREATE TABLE IF NOT EXISTS etf_constituent_sync_status (
  etf_ticker TEXT PRIMARY KEY,
  last_synced_at TEXT,
  status TEXT,
  error TEXT,
  source TEXT,
  records_count INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO etf_watchlists (list_type, parent_sector, industry, ticker, fund_name, sort_order) VALUES
('sector','Materials','Sector ETF','XLB','Materials Select Sector SPDR Fund', 1),
('sector','Communication Services','Sector ETF','XLC','Communication Services Select Sector SPDR Fund', 2),
('sector','Financials','Sector ETF','XLF','Financial Select Sector SPDR Fund', 3),
('sector','Energy','Sector ETF','XLE','Energy Select Sector SPDR Fund', 4),
('sector','Industrials','Sector ETF','XLI','Industrial Select Sector SPDR Fund', 5),
('sector','Health Care','Sector ETF','XLV','Health Care Select Sector SPDR Fund', 6),
('sector','Information Technology','Sector ETF','XLK','Technology Select Sector SPDR Fund', 7),
('sector','Consumer Staples','Sector ETF','XLP','Consumer Staples Select Sector SPDR Fund', 8),
('sector','Real Estate','Sector ETF','XLRE','Real Estate Select Sector SPDR Fund', 9),
('sector','Consumer Discretionary','Sector ETF','XLY','Consumer Discretionary Select Sector SPDR Fund', 10),
('sector','Utilities','Sector ETF','XLU','Utilities Select Sector SPDR Fund', 11);

INSERT OR IGNORE INTO etf_watchlists (list_type, parent_sector, industry, ticker, fund_name, sort_order) VALUES
('industry','Communication Services','Telecom & Media','XTL','SPDR S&P Telecom ETF', 1),
('industry','Communication Services','Telecom & Media','IYZ','iShares U.S. Telecom ETF', 2),
('industry','Communication Services','Telecom & Media','VOX','Vanguard Communication Services ETF', 3),
('industry','Communication Services','Internet & Digital Media','FDN','First Trust Dow Jones Internet ETF', 4),
('industry','Communication Services','Internet & Digital Media','PNQI','Invesco NASDAQ Internet ETF', 5),
('industry','Communication Services','Internet & Digital Media','SOCL','Global X Social Media ETF', 6),
('industry','Information Technology','Semiconductors','SMH','VanEck Semiconductor ETF', 7),
('industry','Information Technology','Semiconductors','SOXX','iShares Semiconductor ETF', 8),
('industry','Information Technology','Semiconductors','XSD','SPDR S&P Semiconductor ETF', 9),
('industry','Information Technology','Semiconductors','PSI','Invesco Semiconductor ETF', 10),
('industry','Information Technology','Software','IGV','iShares Expanded Tech-Software Sector ETF', 11),
('industry','Information Technology','Software','XSW','SPDR S&P Software & Services ETF', 12),
('industry','Information Technology','Software','CLOU','Global X Cloud Computing ETF', 13),
('industry','Information Technology','Software','SKYY','First Trust Cloud Computing ETF', 14),
('industry','Information Technology','Cybersecurity','HACK','ETFMG Prime Cyber Security ETF', 15),
('industry','Information Technology','Cybersecurity','CIBR','First Trust NASDAQ Cybersecurity ETF', 16),
('industry','Information Technology','Cybersecurity','BUG','Global X Cybersecurity ETF', 17),
('industry','Information Technology','AI & Robotics','BOTZ','Global X Robotics & Artificial Intelligence ETF', 18),
('industry','Information Technology','AI & Robotics','ROBO','ROBO Global Robotics & Automation ETF', 19),
('industry','Information Technology','AI & Robotics','ARKQ','ARK Autonomous Technology & Robotics ETF', 20),
('industry','Information Technology','AI & Robotics','IRBO','iShares Robotics and Artificial Intelligence ETF', 21),
('industry','Information Technology','FinTech','FINX','Global X FinTech ETF', 22),
('industry','Information Technology','FinTech','ARKF','ARK Fintech Innovation ETF', 23),
('industry','Health Care','Biotech','IBB','iShares Biotechnology ETF', 24),
('industry','Health Care','Biotech','XBI','SPDR S&P Biotech ETF', 25),
('industry','Health Care','Biotech','FBT','First Trust NYSE Arca Biotechnology ETF', 26),
('industry','Health Care','Pharmaceuticals','IHE','iShares U.S. Pharmaceuticals ETF', 27),
('industry','Health Care','Pharmaceuticals','PJP','Invesco Pharmaceuticals ETF', 28),
('industry','Health Care','Medical Devices','IHI','iShares U.S. Medical Devices ETF', 29),
('industry','Health Care','Medical Devices','XHE','SPDR S&P Health Care Equipment ETF', 30),
('industry','Health Care','Genomics','ARKG','ARK Genomic Revolution ETF', 31),
('industry','Health Care','Genomics','IDNA','iShares Genomics Immunology and Healthcare ETF', 32),
('industry','Industrials','Aerospace & Defense','ITA','iShares U.S. Aerospace & Defense ETF', 33),
('industry','Industrials','Aerospace & Defense','XAR','SPDR S&P Aerospace & Defense ETF', 34),
('industry','Industrials','Aerospace & Defense','PPA','Invesco Aerospace & Defense ETF', 35),
('industry','Industrials','Transportation','IYT','iShares Transportation Average ETF', 36),
('industry','Industrials','Transportation','XTN','SPDR S&P Transportation ETF', 37),
('industry','Industrials','Infrastructure','PAVE','Global X U.S. Infrastructure Development ETF', 38),
('industry','Industrials','Infrastructure','IFRA','iShares U.S. Infrastructure ETF', 39),
('industry','Energy','Oil & Gas','XOP','SPDR S&P Oil & Gas Exploration & Production ETF', 40),
('industry','Energy','Oil & Gas','OIH','VanEck Oil Services ETF', 41),
('industry','Energy','Oil & Gas','IEO','iShares U.S. Oil & Gas Exploration & Production ETF', 42),
('industry','Energy','Clean Energy','ICLN','iShares Global Clean Energy ETF', 43),
('industry','Energy','Clean Energy','TAN','Invesco Solar ETF', 44),
('industry','Energy','Clean Energy','PBW','Invesco WilderHill Clean Energy ETF', 45),
('industry','Financials','Banks','KBE','SPDR S&P Bank ETF', 46),
('industry','Financials','Banks','KRE','SPDR S&P Regional Banking ETF', 47),
('industry','Financials','Banks','IAT','iShares U.S. Regional Banks ETF', 48),
('industry','Financials','Insurance','KIE','SPDR S&P Insurance ETF', 49),
('industry','Financials','Insurance','IAK','iShares U.S. Insurance ETF', 50),
('industry','Financials','Capital Markets','KCE','SPDR S&P Capital Markets ETF', 51),
('industry','Financials','Capital Markets','IAI','iShares U.S. Broker-Dealers & Securities Exchanges ETF', 52),
('industry','Materials','Metals & Mining','XME','SPDR S&P Metals & Mining ETF', 53),
('industry','Materials','Metals & Mining','PICK','iShares MSCI Global Metals & Mining ETF', 54),
('industry','Materials','Metals & Mining','SLX','VanEck Steel ETF', 55),
('industry','Materials','Gold Miners','GDX','VanEck Gold Miners ETF', 56),
('industry','Materials','Gold Miners','RING','iShares MSCI Global Gold Miners ETF', 57),
('industry','Materials','Silver Miners','SIL','Global X Silver Miners ETF', 58),
('industry','Materials','Lithium & Battery Materials','LIT','Global X Lithium & Battery Tech ETF', 59),
('industry','Materials','Lithium & Battery Materials','BATT','Amplify Lithium & Battery Technology ETF', 60),
('industry','Real Estate','Broad REITs','VNQ','Vanguard Real Estate ETF', 61),
('industry','Real Estate','Broad REITs','IYR','iShares U.S. Real Estate ETF', 62),
('industry','Real Estate','Mortgage REITs','REM','iShares Mortgage Real Estate ETF', 63),
('industry','Real Estate','Data Infrastructure REITs','SRVR','Pacer Benchmark Data & Infrastructure Real Estate ETF', 64),
('industry','Consumer Discretionary','Retail','XRT','SPDR S&P Retail ETF', 65),
('industry','Consumer Discretionary','Retail','ONLN','ProShares Online Retail ETF', 66),
('industry','Consumer Discretionary','Homebuilders','XHB','SPDR S&P Homebuilders ETF', 67),
('industry','Consumer Discretionary','Homebuilders','ITB','iShares U.S. Home Construction ETF', 68),
('industry','Consumer Discretionary','EV & Future Mobility','DRIV','Global X Autonomous & Electric Vehicles ETF', 69),
('industry','Consumer Discretionary','EV & Future Mobility','IDRV','iShares Self-Driving EV and Tech ETF', 70),
('industry','Consumer Staples','Food & Beverage','PBJ','Invesco Dynamic Food & Beverage ETF', 71),
('industry','Consumer Staples','Food & Beverage','FTXG','First Trust Nasdaq Food & Beverage ETF', 72),
('industry','Consumer Staples','Agribusiness','MOO','VanEck Agribusiness ETF', 73),
('industry','Utilities','Broad Utilities','XLU','Utilities Select Sector SPDR Fund', 74),
('industry','Utilities','Broad Utilities','VPU','Vanguard Utilities ETF', 75),
('industry','Utilities','Broad Utilities','UTES','Virtus Reaves Utilities ETF', 76);

INSERT OR IGNORE INTO symbols (ticker, name, exchange, asset_class, sector, industry) VALUES
('ARKF','ARK Fintech Innovation ETF','NYSEARCA','etf','Information Technology','FinTech'),
('ARKG','ARK Genomic Revolution ETF','NYSEARCA','etf','Health Care','Genomics'),
('ARKQ','ARK Autonomous Technology & Robotics ETF','NYSEARCA','etf','Information Technology','AI & Robotics'),
('BATT','Amplify Lithium & Battery Technology ETF','NYSEARCA','etf','Materials','Lithium & Battery Materials'),
('BOTZ','Global X Robotics & Artificial Intelligence ETF','NYSEARCA','etf','Information Technology','AI & Robotics'),
('BUG','Global X Cybersecurity ETF','NYSEARCA','etf','Information Technology','Cybersecurity'),
('CIBR','First Trust NASDAQ Cybersecurity ETF','NYSEARCA','etf','Information Technology','Cybersecurity'),
('CLOU','Global X Cloud Computing ETF','NYSEARCA','etf','Information Technology','Software'),
('DRIV','Global X Autonomous & Electric Vehicles ETF','NYSEARCA','etf','Consumer Discretionary','EV & Future Mobility'),
('FBT','First Trust NYSE Arca Biotechnology ETF','NYSEARCA','etf','Health Care','Biotech'),
('FDN','First Trust Dow Jones Internet ETF','NYSEARCA','etf','Communication Services','Internet & Digital Media'),
('FINX','Global X FinTech ETF','NYSEARCA','etf','Information Technology','FinTech'),
('FTXG','First Trust Nasdaq Food & Beverage ETF','NYSEARCA','etf','Consumer Staples','Food & Beverage'),
('GDX','VanEck Gold Miners ETF','NYSEARCA','etf','Materials','Gold Miners'),
('HACK','ETFMG Prime Cyber Security ETF','NYSEARCA','etf','Information Technology','Cybersecurity'),
('IAI','iShares U.S. Broker-Dealers & Securities Exchanges ETF','NYSEARCA','etf','Financials','Capital Markets'),
('IAK','iShares U.S. Insurance ETF','NYSEARCA','etf','Financials','Insurance'),
('IAT','iShares U.S. Regional Banks ETF','NYSEARCA','etf','Financials','Banks'),
('IBB','iShares Biotechnology ETF','NYSEARCA','etf','Health Care','Biotech'),
('ICLN','iShares Global Clean Energy ETF','NYSEARCA','etf','Energy','Clean Energy'),
('IDNA','iShares Genomics Immunology and Healthcare ETF','NYSEARCA','etf','Health Care','Genomics'),
('IDRV','iShares Self-Driving EV and Tech ETF','NYSEARCA','etf','Consumer Discretionary','EV & Future Mobility'),
('IEO','iShares U.S. Oil & Gas Exploration & Production ETF','NYSEARCA','etf','Energy','Oil & Gas'),
('IFRA','iShares U.S. Infrastructure ETF','NYSEARCA','etf','Industrials','Infrastructure'),
('IGV','iShares Expanded Tech-Software Sector ETF','NYSEARCA','etf','Information Technology','Software'),
('IHE','iShares U.S. Pharmaceuticals ETF','NYSEARCA','etf','Health Care','Pharmaceuticals'),
('IHI','iShares U.S. Medical Devices ETF','NYSEARCA','etf','Health Care','Medical Devices'),
('IRBO','iShares Robotics and Artificial Intelligence ETF','NYSEARCA','etf','Information Technology','AI & Robotics'),
('ITA','iShares U.S. Aerospace & Defense ETF','NYSEARCA','etf','Industrials','Aerospace & Defense'),
('ITB','iShares U.S. Home Construction ETF','NYSEARCA','etf','Consumer Discretionary','Homebuilders'),
('IYR','iShares U.S. Real Estate ETF','NYSEARCA','etf','Real Estate','Broad REITs'),
('IYT','iShares Transportation Average ETF','NYSEARCA','etf','Industrials','Transportation'),
('IYZ','iShares U.S. Telecom ETF','NYSEARCA','etf','Communication Services','Telecom & Media'),
('KBE','SPDR S&P Bank ETF','NYSEARCA','etf','Financials','Banks'),
('KCE','SPDR S&P Capital Markets ETF','NYSEARCA','etf','Financials','Capital Markets'),
('KIE','SPDR S&P Insurance ETF','NYSEARCA','etf','Financials','Insurance'),
('KRE','SPDR S&P Regional Banking ETF','NYSEARCA','etf','Financials','Banks'),
('LIT','Global X Lithium & Battery Tech ETF','NYSEARCA','etf','Materials','Lithium & Battery Materials'),
('MOO','VanEck Agribusiness ETF','NYSEARCA','etf','Consumer Staples','Agribusiness'),
('OIH','VanEck Oil Services ETF','NYSEARCA','etf','Energy','Oil & Gas'),
('ONLN','ProShares Online Retail ETF','NYSEARCA','etf','Consumer Discretionary','Retail'),
('PAVE','Global X U.S. Infrastructure Development ETF','NYSEARCA','etf','Industrials','Infrastructure'),
('PBJ','Invesco Dynamic Food & Beverage ETF','NYSEARCA','etf','Consumer Staples','Food & Beverage'),
('PBW','Invesco WilderHill Clean Energy ETF','NYSEARCA','etf','Energy','Clean Energy'),
('PICK','iShares MSCI Global Metals & Mining ETF','NYSEARCA','etf','Materials','Metals & Mining'),
('PJP','Invesco Pharmaceuticals ETF','NYSEARCA','etf','Health Care','Pharmaceuticals'),
('PNQI','Invesco NASDAQ Internet ETF','NYSEARCA','etf','Communication Services','Internet & Digital Media'),
('PPA','Invesco Aerospace & Defense ETF','NYSEARCA','etf','Industrials','Aerospace & Defense'),
('PSI','Invesco Semiconductor ETF','NYSEARCA','etf','Information Technology','Semiconductors'),
('REM','iShares Mortgage Real Estate ETF','NYSEARCA','etf','Real Estate','Mortgage REITs'),
('RING','iShares MSCI Global Gold Miners ETF','NYSEARCA','etf','Materials','Gold Miners'),
('ROBO','ROBO Global Robotics & Automation ETF','NYSEARCA','etf','Information Technology','AI & Robotics'),
('SIL','Global X Silver Miners ETF','NYSEARCA','etf','Materials','Silver Miners'),
('SKYY','First Trust Cloud Computing ETF','NYSEARCA','etf','Information Technology','Software'),
('SLX','VanEck Steel ETF','NYSEARCA','etf','Materials','Metals & Mining'),
('SMH','VanEck Semiconductor ETF','NYSEARCA','etf','Information Technology','Semiconductors'),
('SOCL','Global X Social Media ETF','NYSEARCA','etf','Communication Services','Internet & Digital Media'),
('SOXX','iShares Semiconductor ETF','NYSEARCA','etf','Information Technology','Semiconductors'),
('SRVR','Pacer Benchmark Data & Infrastructure Real Estate ETF','NYSEARCA','etf','Real Estate','Data Infrastructure REITs'),
('TAN','Invesco Solar ETF','NYSEARCA','etf','Energy','Clean Energy'),
('UTES','Virtus Reaves Utilities ETF','NYSEARCA','etf','Utilities','Broad Utilities'),
('VNQ','Vanguard Real Estate ETF','NYSEARCA','etf','Real Estate','Broad REITs'),
('VOX','Vanguard Communication Services ETF','NYSEARCA','etf','Communication Services','Telecom & Media'),
('VPU','Vanguard Utilities ETF','NYSEARCA','etf','Utilities','Broad Utilities'),
('XAR','SPDR S&P Aerospace & Defense ETF','NYSEARCA','etf','Industrials','Aerospace & Defense'),
('XBI','SPDR S&P Biotech ETF','NYSEARCA','etf','Health Care','Biotech'),
('XHB','SPDR S&P Homebuilders ETF','NYSEARCA','etf','Consumer Discretionary','Homebuilders'),
('XHE','SPDR S&P Health Care Equipment ETF','NYSEARCA','etf','Health Care','Medical Devices'),
('XLB','Materials Select Sector SPDR Fund','NYSEARCA','etf','Materials','Sector ETF'),
('XLC','Communication Services Select Sector SPDR Fund','NYSEARCA','etf','Communication Services','Sector ETF'),
('XLE','Energy Select Sector SPDR Fund','NYSEARCA','etf','Energy','Sector ETF'),
('XLF','Financial Select Sector SPDR Fund','NYSEARCA','etf','Financials','Sector ETF'),
('XLI','Industrial Select Sector SPDR Fund','NYSEARCA','etf','Industrials','Sector ETF'),
('XLK','Technology Select Sector SPDR Fund','NYSEARCA','etf','Information Technology','Sector ETF'),
('XLP','Consumer Staples Select Sector SPDR Fund','NYSEARCA','etf','Consumer Staples','Sector ETF'),
('XLRE','Real Estate Select Sector SPDR Fund','NYSEARCA','etf','Real Estate','Sector ETF'),
('XLU','Utilities Select Sector SPDR Fund','NYSEARCA','etf','Utilities','Sector ETF'),
('XLV','Health Care Select Sector SPDR Fund','NYSEARCA','etf','Health Care','Sector ETF'),
('XLY','Consumer Discretionary Select Sector SPDR Fund','NYSEARCA','etf','Consumer Discretionary','Sector ETF'),
('XME','SPDR S&P Metals & Mining ETF','NYSEARCA','etf','Materials','Metals & Mining'),
('XOP','SPDR S&P Oil & Gas Exploration & Production ETF','NYSEARCA','etf','Energy','Oil & Gas'),
('XRT','SPDR S&P Retail ETF','NYSEARCA','etf','Consumer Discretionary','Retail'),
('XSD','SPDR S&P Semiconductor ETF','NYSEARCA','etf','Information Technology','Semiconductors'),
('XSW','SPDR S&P Software & Services ETF','NYSEARCA','etf','Information Technology','Software'),
('XTL','SPDR S&P Telecom ETF','NYSEARCA','etf','Communication Services','Telecom & Media'),
('XTN','SPDR S&P Transportation ETF','NYSEARCA','etf','Industrials','Transportation');